### ISSUE TITLE
Tool specific misc option - refactoring

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#152]
Connected to #150, and #149 . The parsing helps to understand the xml format of tools better which will lead to unification of misc options.

An example what I have at the moment for IAR and uVision.

```
iar:
        misc:
            ICCARM:
                data:
                    option:
                        CCDebugInfo:
                            - enable
                        CCOptLevel:
                            - 1
                        IccLang:
                            - 1
                        IccCppDialect:
                            - 2
            General:
                data:
                    option:
                        GRuntimeLibSelect:
                            - 2
            AARM:
                data:
                    option:
                        ACaseSensitivity:
                            - enable
                        ADebug:
                            - enable
```

and uvision:

```
        misc:
            Cads:
                MiscControls:
                    - --debug -g --gnu
                Ropi:
                    - enable
                Optim:
                    - 1
                uC99:
                    - enable
                OneElfS:
                    - enable
```

The result should be that these misc options are as close as to the xml format as possible. This will be another v0.6 breaking change, but if we do it right, should stay for a while :smile: The misc will be supported,the template will be easy-to-use option, as this misc needs some knowledge about all available option.
