### ISSUE TITLE
Virtual dir (group_name) consolidate

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#153]
This might help to implement #146, the key can be only once, the code illustrates the problem:

```
projects:
  first_project:
    common:
      group_name:
        - name
     sources:
       - file.c
       - file2.cpp
```
For all sources, only  one virtual dir. It would probably be bettter to group sources:

```
projects:
  first_project:
    common:
      sources:
        group_one: #virtual dir, all files below in the list belong to this group
          - file.c
        group_two: #virtual dir
          - file2.cpp
```
