### ISSUE TITLE
Grouping of projects

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#188]
On my way  to support workspaces, I implemented a new feature, which we might want to add. Grouping of projects.

Works as, that a user creates a group of projects.

```
projects:
  bootloader:
    freescale_bootloader:
      - files
    nxp_bootloader:
      - files
  flasher:
    freescale_flasher:
      - files
  project_no_group:
    - files
```

pgen export -p bootloader or should be valid also pgen export -p nxp_bootloader
