### ISSUE TITLE
Debugger - extend to interface

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#324]
Progen definitions define debugger with a name and an interface, we should provide this option to projects 

```
debugger:
- j-link
#or
debugger:
  name:
  - j-link
  interface:
  - swd
```
