### ISSUE TITLE
Nested virtual dirs support

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#374]
it's currently only one level of virtual dirs supported. We could add more, at least increase the limit to 5.

```
common:
  sources:
    first_dir:
     second_dir:
       - file
```
