### ISSUE TITLE
Make flat projects.yaml acceptable

### ISSUE THREAD

**Issue by sarahmarshy** [project-generator/project_generator#414]
Currently, progen **only** accepts projects.yaml file in the form of:

```
projects:
    project_name:
         - yaml_with_source.yaml
         - another_yaml_with_source.yaml
```
where yaml_with_source.yaml looks like:
```
common:
    includes:
        - path\to\include
        - another\path
   sources:
       - path\to\source
      group:
      - grouped\source
```

I think it should accept projects.yaml files that look like:
```
projects:
    project_name:
         common:
              includes:
                  - path\to\include
                  - another\path
              sources:
                  - path\to\source
                  group:
                  - grouped\source
```

cc @0xc0170 @sg-
