### ISSUE TITLE
Makefile: flags should not need `-`, same as std libs

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#469]
```
tool_specific:
    gcc_arm:
        misc:
            c_flags:
                - -mfpu=fpv4-sp-d16
                - -mfloat-abi=softfp
                - -g 
                - -ggdb
                - -Os 
                - -Wall 
                - -fno-strict-aliasing
                - -ffunction-sections 
                - -fdata-sections 
                - -fno-exceptions 
                - -fno-delete-null-pointer-checks
                - -fmessage-length=0 
                - -fno-builtin 
                - -mthumb
                - -mcpu=cortex-m4
                - -MMD
                - -MP
```

this should be without `-`, as we parse them and add `-`
