### ISSUE TITLE
linker script: should not be under misc in tools

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#470]
I misplaced linker script in one of the records, and it failed to produce correct path (relative to the generated project):

correct:

```
tool_specific:
    gcc_arm:
        linker_file:
            - cmsis/MK64F12/MK64F12.ld
```

incorrect but no error:

```
tool_specific:
    gcc_arm:
        misc:
            linker_file:
                - cmsis/MK64F12/MK64F12.ld

```
