### ISSUE TITLE
Set default values for templates

### ISSUE THREAD

**Issue by 0xc0170** [project-generator/project_generator#61]
Project like 

```
common:
  board:
  - frdm-k64f
  include_paths:
  - \gpio_demo_twrk20d72
  - \gpio_demo_twrk20d72\common
  - \gpio_demo_twrk20d72\cpu
  - \gpio_demo_twrk20d72\cpu\headers
  linker_file:
  - \gpio_demo_twrk20d72\k20x256_flash.ld
  source_files:
  - \gpio_demo_twrk20d72\main.c
  - \gpio_demo_twrk20d72\cpu\startup_k20.c
  - \gpio_demo_twrk20d72\cpu\system_k20.c
```

Should be able to export and compile , as least this one for arm gcc. Or even for uvision, although it does not accept .ld files.
